-- "user".tb_natural_person definition

-- Drop table

-- DROP TABLE "user".tb_natural_person;

CREATE TABLE "user".tb_natural_person (
    id_natural_person int8 GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
    ) NOT NULL,
    e_mail varchar(200) NOT NULL,
    "name" varchar(64) NOT NULL,
    surname varchar(128) NOT NULL,
    "document" varchar(11) NOT NULL,
    "password" text NULL,
    "token" text NULL,
    status bool DEFAULT true NOT NULL,
    dt_created timestamptz NOT NULL,
    dt_updated timestamptz NOT NULL,
    "role" varchar(10) NULL,
    CONSTRAINT pk_tb_natural_person PRIMARY KEY (id_natural_person),
    CONSTRAINT uq_tb_natural_person_email UNIQUE (e_mail)
);